language: php

php:
  - 5.5

services:
  - mongodb
  - memcached

before_install:
  - mysql -e "CREATE DATABASE IF NOT EXISTS vegas_test;" -uroot
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
  - echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | sudo tee /etc/apt/sources.list.d/mongodb.list
  - sudo apt-get update
  - sudo apt-get install mongodb-org-server

before_script:
  - git clone -q --depth=1 https://github.com/phalcon/cphalcon.git -b phalcon-v2.0.10
  - (cd cphalcon/ext; export CFLAGS="-g3 -O1 -fno-delete-null-pointer-checks -Wall"; phpize && ./configure --enable-phalcon && make -j4 && sudo make install && phpenv config-add ../unit-tests/ci/phalcon.ini)
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev
  
script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c travis/phpunit.xml.dist

after_script:
  - php vendor/bin/coveralls -v
